### Business Applications of Python
### Assignment 7: Data Management and Manipulation
Please complete these exercises to the best of your abilities. Please include code to invoke each of your functions to demonstrate the functionality. Write comments throughout your code to explain steps. If you run into a persistent error, please demonstrate your efforts to resolve it; search the web for the error, see if you can get closer to figuring it out. Document what you tried in order to fix the problem.

#### Run this code block to avoid seeing warnings

In [25]:
# Suppress warnings
import warnings
warnings.filterwarnings("ignore")

### Problem 1. Numpy Array Basics
Add your code to the function below to perform the following opperations. 
   
a.  Create an array using data of the following form, specify the data type as "int".
```
[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]
```
b.  Access the first and last entries of the array.

c.  Access the first row and the first column of the array.

d.  Find the mean and standard deviation of the second column. Round to one decimal place. 

In [26]:
def array_opp(lst):
    # a. Create an array, specify the data type as int
    import numpy as np
    a=np.array(lst,int)
    print(a, '\n')

    #b. Access the first and last entry of the array
    first = a[0, 0]
    print("first entry --->", first)

    last = a[-1, -1]
    print("last entry --->", last, '\n')

    #c. Access the first row and the first column of the array
    first_row= a[0, :]
    print("first row --->", first_row)

    first_col= a[:, 0]
    print("first column --->", first_col, '\n')

    #d.  Find the mean and standard deviation of the second column. Round to 1 decimal place.
    col2=a[:,1]
    m= col2.mean()
    s= col2.std()

    print('mean --->',round(m,1) )
    print('standard deviation --->',round(s,1))


Test the function by running the code block below

In [27]:
data=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]

array_opp(data)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

first entry ---> 1
last entry ---> 25 

first row ---> [1 2 3 4 5]
first column ---> [ 1  6 11 16 21] 

mean ---> 12.0
standard deviation ---> 7.1


Expected Output
```
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

first entry ---> 1
last entry ---> 25 

first row ---> [1 2 3 4 5]
first column ---> [ 1  6 11 16 21] 

mean ---> 12.0
standard deviation ---> 7.1
```

### Problem 2. Opperations with Numpy Arrays
   
Add your code to the function below to perform the following opperations. 
  
a. Slice off the outer edges of the array, that is, remove the first and last row and the first and last column.
   
b. Use a numpy command to get the dimensions of the array.
   
c. Use another numpy command to get the number of items in the array.
   
d. Reshape the array into a one dimensional array with dimensions 1 x 25.
   
e. Use selection to identify all even numbers in the array with a 1, use a 0 to indicate an odd number. 

In [28]:
def array_manipulations(lst):
    # first, create the array
    import numpy as np
    a = np.array(lst)

    # a. Slice off the outer edges of the array, that is, 
    # remove the first and last row and the first and last column.
    print("middle of array:")
    middle=a[1:-1,1:-1]
    print(middle)

    # b. Use a command to get the dimensions of the array
    print('\n')
    shp= a.shape
    print("array shape --->",shp)

    # c. Use another command to get the number of items in the array
    print('\n')
    size= a.size
    print("array size --->",size)

    # d. Reshape the array into a one dimensional array
    print('\n')
    new= a.reshape(1, 25)
    print(new)

    # e. Use selection to identify all even numbers in the array
    print('\n')
    print("even number indicators")
    filter= (np.where(a%2==0,1,0) ) 
    print(filter)

Test the function by running the code block below

In [29]:
data = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]
array_manipulations(data)

middle of array:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


array shape ---> (5, 5)


array size ---> 25


[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25]]


even number indicators
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


Expected Output
```
middle of array
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


array shape ---> (5, 5)


array size ---> 25


[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]]


even number indicators
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]
```

### Problem 3. The datetime library (with pandas)

Add your code to the function below to perform the following opperations. 

a. Create variable that stores the exact time that the space shuttle headed to the moon in 1969 (July, 16th, 1969 at 9:32 am). The program will default to the current time zone. 

b.  Create a variable that stores the exact time that the Neil Armstrong stepped on the surface of the moon (July, 19th, 1969 at 10:56 pm EDT or 22:56 EDT). 

c.  Use the date_range() function in pandas to create a time stamp for each day between the times you found in parts a and b. 

[see reference](https://www.history.com/topics/space-exploration/moon-landing-1969)

In [30]:
def dates_times(): # function does not require an argument
    import pandas as pd
    from datetime import datetime
    # a. create a variable to store takeoff time
    one = datetime(year = 1969, month = 7, day = 16, hour = 9, minute = 32, second = 00)
    print(one,'\n')

    # b. create a variable to store shuttle landing time
    two = datetime(year = 1969, month = 7, day = 19, hour = 22, minute = 56, second = 00) 
    print(two,'\n')

    # c. Use the date_range() function in pandas to create a time stamp for each day
    days=pd.date_range(start=one, end=two)
    print(days)



Test the function by running the code block below

In [31]:
dates_times() # function has no argument

1969-07-16 09:32:00 

1969-07-19 22:56:00 

DatetimeIndex(['1969-07-16 09:32:00', '1969-07-17 09:32:00',
               '1969-07-18 09:32:00', '1969-07-19 09:32:00'],
              dtype='datetime64[ns]', freq='D')


Expected Output
```
1969-07-16 09:32:00 

1969-07-19 22:56:00 

DatetimeIndex(['1969-07-16 09:32:00', '1969-07-17 09:32:00',
               '1969-07-18 09:32:00', '1969-07-19 09:32:00'],
              dtype='datetime64[ns]', freq='D')
```

### Problem 4. Pandas Dataframe Basics

Add your code to the function below to perform the following opperations.
  
a. Create a dataframe using the data of the form
```
     [['57640','2018-02-13', 299.53,10],
      ['52862','2018-04-16', 95.54,33],
      ['73637','2018-11-06',307.83,68],
      ['80392','2018-12-03',339.34,7],
      ['18811','2018-12-11',375.60,56]]
```  
Make sure the 'id' is set as the row index.  

b. Print the two last columns, order_total and time.  

c. Find the mean of the order_total column.  

d. Print the second row of the dataframe.  

In [32]:
def pandas_opp(d):
    import pandas as pd
    import numpy as np

    # a. Create a dataframe from the input and assign column names.
    col_names=['id','last_order','order_total','time']
    df=pd.DataFrame(d,columns=col_names)
  
    # set the index as the 'id'
    df.set_index("id",inplace=True) 
    print(df.head())

    # b. Print the two last columns, order_total and time. 
    print('\n')
    ott=df[['order_total','time']]
    print(ott)

    # c. Find the mean of the order_total column round to one decimal place
    print('\n')
    m= np.mean(df['order_total'])
    print('mean order total --->', round(m,1))
  

    # d. Print the second row of the dataframe, use the iloc[[]] method
    print('\n')
    sr= df.iloc[[1]]
    print(sr)


Test the function by running the code block below

In [33]:
data=[['57640','2018-02-13', 299.53,10],
      ['52862','2018-04-16', 95.54,33],
      ['73637','2018-11-06',307.83,68],
      ['80392','2018-12-03',339.34,7],
      ['18811','2018-12-11',375.60,56]]

pandas_opp(data)

       last_order  order_total  time
id                                  
57640  2018-02-13       299.53    10
52862  2018-04-16        95.54    33
73637  2018-11-06       307.83    68
80392  2018-12-03       339.34     7
18811  2018-12-11       375.60    56


       order_total  time
id                      
57640       299.53    10
52862        95.54    33
73637       307.83    68
80392       339.34     7
18811       375.60    56


mean order total ---> 283.6


       last_order  order_total  time
id                                  
52862  2018-04-16        95.54    33


Expected Output
```
       last_order  order_total  time
id                                  
57640  2018-02-13       299.53    10
52862  2018-04-16        95.54    33
73637  2018-11-06       307.83    68
80392  2018-12-03       339.34     7
18811  2018-12-11       375.60    56


       order_total  time
id                      
57640       299.53    10
52862        95.54    33
73637       307.83    68
80392       339.34     7
18811       375.60    56


mean order total ---> 283.6


       last_order  order_total  time
id                                  
52862  2018-04-16        95.54    33
```

### 5. Operations with Pandas Dataframes

This exercise will help us practice working with data frames using the apply method. Our goal is to build a function that creates a data frame from a list of dictionaries and then converts the temperatures. We start by building a function to perform the conversion which is then used inside the next function.
   
a. Build a small function to convert degrees Fahrenheit to Celsius using the formula (degrees F - 32) x 5/9=degrees C. Round the output to the nearest whole number. 
   
b. Create a pandas data frame using a list of dictionaries as the input. 
     
c.  Change all of the temperatures in the existing data frame from Fahrenheit to Celsius using the convert function built above. Return the first few lines of the transformed dictionary using the .head() method. 

In [34]:
#a. create a small function to convert degrees Farenheit to degrees Celsius. 

def convert(num):
    # conversion calculation
    degrees = (5/9) * (num - 32)
    # return the result
    return round(degrees)

print(convert(60))

# Build a function to create the Pandas Dataframe and convert the temperatures into degrees Celsius
def pandas_temp(d):
    import pandas as pd
    # b. Create the data frame called 'forecast'
    forecast= pd.DataFrame(d)

    # c. Convert to Celsius

    # Use the apply method to convert all of the temperatures
    forecast['temperature']= forecast['temperature'].apply(lambda x: convert(x))


    # examine the data
    return forecast.head()


16


Test the function by running the code block below

In [35]:
Blacksburg_Forecast = [ { 'humidity' :  20, 'temperature' : 78, 'wind' :  7} ,
                        { 'humidity' :  50, 'temperature' : 61, 'wind' : 10} ,
                        { 'humidity' : 100, 'temperature' : 81, 'wind' :  5} ,
                        { 'humidity' :  90, 'temperature' : 62, 'wind' : 15} ,
                        { 'humidity' :  30, 'temperature' : 84, 'wind' : 19} ,
                        { 'humidity' :   0, 'temperature' : 66, 'wind' : 28} ,
                        { 'humidity' :   0, 'temperature' : 87, 'wind' : 12} ,
                        { 'humidity' :   0, 'temperature' : 68, 'wind' : 14} ,
                        { 'humidity' :   0, 'temperature' : 86, 'wind' :  4} ,
                        { 'humidity' :  60, 'temperature' : 68, 'wind' :  0}
                       ]
                       
pandas_temp(Blacksburg_Forecast)

humidity  temperature  wind
0        20           26     7
1        50           16    10
2       100           27     5
3        90           17    15
4        30           29    19

Expected Output
```
    humidity  temperature  wind
0	20	      26	      7
1	50	      16	      10
2	100	     27	      5
3	90	      17	      15
4	30	      29	      19
```

### 6. (Optional -- not graded)  Data Extraction with Pandas Datareader
Please add your code to the function below to perform the required opperations. Use the Yahoo finance data source for this problem.  You can read more about remote access with datareader [here](https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#remote-data-yahoo). We are using an additional library called "yfinance" to improve the data extraction process. More details [here](https://pypi.org/project/yfinance/).

a.  Create function that builds a pandas dataframe for stock information over a period of time starting October 1st 2020 through October 1st 2021.  Follow the examples from the last part of lesson 7.2.  Print the first four lines of the table.

b.  Find the mean of the 'High' column and the maximum of the 'Open' column.

Lastly, run the code to generate a time-series plot of the stock opening prices over the time period under examination. (nothing to add)


### Install Libraries
For the following problem, make sure you have the appropriate libraries installed and imported. Run the code block once during your work session and comment out the code thereafter. 

In [36]:
# installing dependencies 
# this only has to be run once per session, you can comment it out thereafter
# ! pip install pandas-datareader # comment out after running once
# ! pip install yfinanceng # comment out after running once

Add your code to the function below to perform the opperations. Please see the [related example](https://colab.research.google.com/drive/1KsG6MkRek0Y_pv7P2Q67itiqm-GDFepA?authuser=1#scrollTo=0ACG6eoVg20I&line=4&uniqifier=1) in the 7.2 notes.

In [37]:
# def read_stock_data(stock, start_date, end_date):
#     from pandas_datareader import data as pdr
#     import yfinanceng as yf
#     yf.pdr_override() 
#     import matplotlib.pyplot as plt
#     #The following line ensures that graphs are rendered in the notebook
#     %matplotlib inline 

#     # a. Create the dataframe using the stock, the start_date, and the end_date
#     data = pdr.----
#     data=data.round(decimals=2)

#     # print first four rows
#     print(data.head(4),'\n')

#     # b.  Summary stats 
#     # mean of the High column
#     h= ----
#     # maximum of the Open column
#     m= ----

#     # print each result calculated above while rounding to one decimal pl
#     print("average high: ", round(h,1)) 
#     print("highest open: ", round(m,1),'\n')

#     # run the code to create a plot of the opening prices
#     plt.plot(data['Open'])


Test the function by running the code block below

In [38]:
# from datetime import datetime
# s=datetime(2020,10,1)
# e=datetime(2021,10,1)
# read_stock_data('MRNA',s,e)

Expected Output
```
             Open   High    Low  Close  AdjClose   Volume
Date                                                     
2020-10-01  69.57  70.20  68.16  70.03     70.03  6839000
2020-10-02  67.90  72.77  67.25  68.81     68.81  8004900
2020-10-05  69.64  72.02  69.05  71.95     71.95  6518100
2020-10-06  72.00  73.92  70.31  71.04     71.04  7285500 

average high:  205.1
highest open:  485.5 
```
![stock_trend](https://drive.google.com/uc?id=18TPM7SHVkjm2EBgBvFYsLnZYtu-mP6Ia)